hello:
	go run ./cmd/hello/main.go

http:
	go run ./cmd/http/main.go

buid-hello:
	go build -o ./bin/hello ./cmd/hello/main.go

build-http:
	go build -o ./bin/http ./cmd/http/main.go

build-all: build-hello build-http
